### ISSUE TITLE
Gaps in data

### ISSUE THREAD

**Issue by cantrowitz** [doshea/nyt_crosswords#1]
I'm just curious why there are gaps in the data. It seems there is no pattern about what date/day of the week is missing. Any light you could shed would be great. Thanks!

**Comment by doshea** [comment]
Sure, there used to be only two gaps in the coverage because the resource I was deriving the data from was relatively complete. I was also able to automate the initial data scraping at that time. Unfortunately, the open-source resource I was using decided to become mostly-closed source and took steps to break automated scraping. I haven't found a way to re-automate around their cookies...although not for lack of trying. As a result I have to remember and manually upload every day. Unfortunately, the resource only displays each day's puzzle data for that day and is no longer searchable -- meaning that any day I forget is lost. It's really too bad, I was proud of this as an enduring cache of crosswords and now it's sloppy and haphazard.

**Comment by cantrowitz** [comment]
Thanks!
